markdown:         kramdown
highlighter:      rouge

title:            lynx-blog
tagline:          'My personal blog.'
description:      'A blog from programmers.'
url:              https://lynxrenb.github.io
baseurl:          '/hydeout'

author:
  name:           'lynxrenb'
  url:            https://lynxrenb.github.io

paginate:         5

plugins:
  - jekyll-paginate

exclude:
  - README.md

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

sidebar_home_link:  true

hydeout:
  version:          4.2.0
  repo:             https://github.com/fongandrew/hydeout
